# Generated by Django 4.0.3 on 2022-03-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
    ]
