# Generated by Django 4.0.3 on 2022-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_userprofile_agent_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='organisation',
        ),
    ]
