# Generated by Django 4.0.3 on 2022-03-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_remove_agent_organisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
