# Generated by Django 4.0.3 on 2022-03-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_lead_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='lead.userprofile'),
            preserve_default=False,
        ),
    ]
